spring:
#  devtools:
#    livereload:
#      enabled: true ㅁㅁㅁㅁ
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/Qaru_local
    username: user
    password: sos6238*
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace